### ISSUE TITLE
I want to contribute with a PR

### ISSUE THREAD

**Issue by bovacu** [travisdoor/tine#1]
Hey, I'm loving your editor and it seems it is lacking some features I like having, so as it is a public repo, I'm starting to add them myself, so I'd like to be able to create PRs, but I cannot seem to push any branches, therefore cannot make any PR, would you give me permission to push my branch and create features for the tool?

The first I made is a very basic one, it is duplicating the current line, which I think is quite useful. It is my first time with the language and also the project as I downloaded it today, so if there is any code I made wrong, just tell me so I can adapt to your coding style!

Those have been the changes I made:
![image](https://github.com/travisdoor/tine/assets/36163709/acdf4409-1969-48c0-8a05-6ffbbf1fdce2)

**Comment by bovacu** [comment]
Sorry I have just discovered how to create the PR for another user's project on Github, never have done that before

**Comment by travisdoor** [comment]
Hey, no problem! Thanks for the contribution. I've been somewhat busy the last few days. But I'll take a look.

**Comment by bovacu** [comment]
No worries at all!
